# set your python executable path
python_bin: '/nobackup/asouri/TOOLS/miniconda3/bin/python3'

# to run the job on debug queue
debug: False

# number of jobs
num_job: 12

# set the name of CTM model (always CMAQ for AIDA)
ctm_name: 'CMAQ'

# set the path of CTM netcdf files (either relative or absolute)
ctm_dir: 'download_bucket/gmi/'

# the frequency of CTM files (3-hourly)
ctm_freq: '3-hourly'

# should we average CTMs? (reduce memory overhead by a lot)
ctm_avg: True

# error in the model VCD (%)
ctm_error: 50.0

# target gas (NO2, HCHO)
gas: 'NO2'

# the sensor name (OMI, TROPOMI)
sensor: 'TROPOMI'

# consider scattering weights (or AKs) (memory intensive)
read_AK: False

# total column or tropospheric column (only applicable for NO2)
troposphere_only: True

# set the path of L2 files
sat_dir: '/nobackup/asouri/GITS/OI-SAT-GMI/DATA/TROPOMI_NO2/'

# starting date (YYYY-MM) and ending date (YYYY-MM) (the end point will be considered)
start_date: '2022-01'
end_date:   '2022-02'

# output folder for PDF reports
output_pdf_dir: './report_trop_no2_'

# output folder for NC diags
output_nc_dir: './diag_trop_no2_'



