# set your python executable path
python_bin: '/nobackup/asouri/TOOLS/miniconda3/bin/python3'

# to run the job on debug queue
debug: False

# validation only (if True, inversion and assimilation will be set to False)
validation: True

# number of jobs
num_job: 12

# set the name of CTM model (always CMAQ for AIDA)
ctm_name: 'CMAQ'

# set the path of CTM netcdf files (either relative or absolute)
ctm_conc_dir: 'download_bucket/gmi/'

# set the path of MCIP netcdf files (either relative or absolute)
ctm_mcip_dir: 'download_bucket/gmi/'

# set the path of CTM DDM netcdf files (either relative or absolute)
ctm_ddm_dir: 'download_bucket/gmi/'

# set the path of CTM EMISS netcdf files (either relative or absolute)
ctm_emis_dir: 'download_bucket/gmi/'

# should we average CTM outputs to create monthly data? (reduce memory overhead by a lot)
ctm_avg: True

# state vectors
state_vectors: 
   - 'NO2'
   - 'HCHO'
   - 'CO'
   - 'NOx'
   - 'VOC'

sensor:
   - 'TROPOMI'
   - 'TROPOMI'
   - 'MOPITT'
   - 'TROPOMI'
   - 'TROPOMI'


# set the path of L2 files
sat_path:
   - '/c/trop'
   - '/c/trop'
   - '/c/trop'
   - '/c/trop'
   - '/c/trop'

state_vector_conc_errors: # errors for NO2, HCHO, and CO columns in [%]
   - 30
   - 50
   - 50

state_vector_nox_errors: # errors for NOx source (anthro, bio, bb)
   - 30
   - 50
   - 50

state_vector_voc_errors: # errors for NOx source (anthro, bio, bb)
   - 30
   - 50
   - 50

inflate_errors: #inflate the state vector errors (same order as state vectors)
   - 1.0
   - 1.0
   - 1.0
   - 1.0
   - 1.0

# total column or tropospheric column (only applicable for NO2)
troposphere_no2_only: True

# starting date (YYYY-MM) and ending date (YYYY-MM) (the end point will be considered)
start_date: '2022-06'
end_date:   '2022-06'

# output folder for PDF reports
output_pdf_dir: './report'

# output folder for NC diags
output_nc_dir: './diag'



