# set your python executable path
python_bin: '/nobackup/jjung13/miniconda3/bin/python3'

# to run the job on debug queue
debug: True

# validation only (if True, inversion and assimilation will be set to False)
validation: False

# a hack to save outputs in daily for validation purposes 
save_daily: False

# to adjust bias of satellite VCD 
bias_sat: True

index_iteration: # index of iteration
   - 0

# number of jobs
num_job: 12

# set the name of CTM model (always CMAQ for AIDA)
ctm_name: 'CMAQ'

# set the path of CTM netcdf files (either relative or absolute)
ctm_conc_dir: '/nobackup/jjung13/ACMAP_CMAQ_OUT/BASE/2019_const_4D_crt_avis_rdc_lgt_BC/'

# set the path of MCIP netcdf files (either relative or absolute)
ctm_mcip_dir: '/nobackup/jjung13/ACMAP_mcipout/2019/'

# set the path of CTM DDM netcdf files (either relative or absolute)
ctm_ddm_dir: 
   - '/nobackup/jjung13/ACMAP_CMAQ_OUT/DDM/2019_NOX/'
   - '/nobackup/jjung13/ACMAP_CMAQ_OUT/DDM/2019_VOC/'

# set the path of CTM EMISS netcdf files (either relative or absolute)
ctm_emis_dir: '/nobackup/jjung13/ACMAP_4D_EMIS/2019/sources/'

# state vectors
state_vectors: 
   - 'NOx'
   - 'VOC'

sensor:
   - 'TROPOMI'
   - 'TROPOMI'

# set the path of L2 files
sat_path:
   - '/nobackup/jjung13/ACMAP_satellite/TROPOMI_NO2/'
   - '/nobackup/jjung13/ACMAP_satellite/TROPOMI_HCHO/'

state_vector_conc_errors: # errors for NO2, HCHO, and CO columns in [%]
   - 30.0
   - 50.0
   - 50.0

state_vector_nox_errors: # errors for NOx source (anthro, bio, bb, light)
   - 50.0
   - 200.0
   - 300.0
   - 300.0

state_vector_voc_errors: # errors for VOC source (anthro, bio, bb)
   - 30.0
   - 50.0
   - 50.0
   - 0.0

inflate_errors: #inflate the state vector errors (same order as state vectors)
   - 1.0
   - 1.0
   - 1.0
   - 1.0
   - 1.0

# total column or tropospheric column (only applicable for NO2)
troposphere_no2_only: True


# starting date (YYYY-MM) and ending date (YYYY-MM) (the end point will be considered)
start_date: '2019-05'
end_date:   '2019-05'

# output folder for PDF reports
output_pdf_dir: './report_iv'

# output folder for NC diags
output_nc_dir: './diag_iv'



