# set your python executable path
python_bin: '/nobackup/asouri/TOOLS/miniconda3/bin/python3'

# to run the job on debug queue
debug: False

# inversion (True) or validation only (False)
inversion: False

# number of jobs
num_job: 12

# set the name of CTM model (always CMAQ for AIDA)
ctm_name: 'CMAQ'

# set the path of CTM netcdf files (either relative or absolute)
ctm_dir: 'download_bucket/gmi/'

# set the path of CTM DDM netcdf files (either relative or absolute)
ctm_ddm_dir: 'download_bucket/gmi/'

# set the path of CTM EMISS netcdf files (either relative or absolute)
ctm_emiss_dir: 'download_bucket/gmi/'

# should we average CTM outputs to create monthly data? (reduce memory overhead by a lot)
ctm_avg: True

# state vectors
state_vectors: 
   - 'NO2'
   - 'HCHO'
   - 'NOx'
   - 'VOC'
   - 'CO'

state_vector_errors: # errors for NO2 and HCHO columns in [%]
   - 30
   - 50

inflate_errors: #inflate the state vector errors
   - 1.0
   - 1.0
   - 1.0
   - 1.0
   - 1.0

# the sensor name for NO2 and HCHO (OMI, TROPOMI), for CO, we will always use MOPITT
sensor: 'TROPOMI'

# consider scattering weights (or AKs) (memory intensive)
read_AK: True

# total column or tropospheric column (only applicable for NO2)
troposphere_only: True

# set the path of L2 files
sat_dir_no2: '/nobackup/asouri/GITS/OI-SAT-GMI/DATA/TROPOMI_NO2/'
sat_dir_hcho: '/nobackup/asouri/GITS/OI-SAT-GMI/DATA/TROPOMI_HCHO/'
sat_dir_co: '/nobackup/asouri/GITS/OI-SAT-GMI/DATA/TROPOMI_HCHO/'

# starting date (YYYY-MM) and ending date (YYYY-MM) (the end point will be considered)
start_date: '2022-06'
end_date:   '2022-06'

# output folder for PDF reports
output_pdf_dir: './report'

# output folder for NC diags
output_nc_dir: './diag'



